title: Frigate Discord Video Receiver
description: High-resolution recorded event video clip notification bridge from Frigate NVR to Discord.
show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
